---
mattermost_version: "9.11.0"
mattermost_docker_image: "ghcr.io/zr0x8/mattermost"
mattermost_deploy_dir: "/opt/mattermost"
web_host: "{{ hostvars[groups['web'][0]]['web_public_ip'] }}"
db_host: "{{ secret_db_ip }}"

zabbix_deploy_dir: "/opt/zabbix"
zabbix_web_port: "{{ secret_zabbix_web_port }}"
zabbix_server_port: "{{ secret_zabbix_server_port }}"
zabbix_db_name: "{{ secret_zabbix_db_name }}"
zabbix_db_user: "{{ secret_zabbix_db_user }}"
zabbix_db_password: "{{ secret_zabbix_db_password }}"
zabbix_timezone: "Asia/Ho_Chi_Minh"
