---
- name: Create mattermost group
  group:
    name: "{{ mattermost_group }}"
    system: yes

- name: Create mattermost user
  user:
    name: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"
    system: yes
    create_home: no

- name: Install Docker and dependencies
  apt:
    name:
      - docker.io
      - python3-docker
    state: present
    update_cache: yes

- name: Ensure Docker is running and enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create mattermost directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"
    mode: '0755'
  loop:
    - "{{ mattermost_deploy_dir }}"
    - "{{ mattermost_deploy_dir }}/data"
    - "{{ mattermost_deploy_dir }}/config"
    - "{{ mattermost_deploy_dir }}/logs"
    - "{{ mattermost_deploy_dir }}/plugins"
    - "{{ mattermost_deploy_dir }}/client/plugins"

- name: Configure Mattermost
  template:
    src: config.json.j2
    dest: "{{ mattermost_deploy_dir }}/config/config.json"
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"
  notify: Restart Mattermost Container

- name: Pull Mattermost Docker image
  community.docker.docker_image:
    name: "{{ mattermost_docker_image }}:{{ image_tag | default('latest') }}"
    source: pull

- name: Run Mattermost container
  community.docker.docker_container:
    name: mattermost
    image: "{{ mattermost_docker_image }}:{{ image_tag | default('latest') }}"
    state: started
    restart_policy: always
    ports:
      - "{{ mattermost_port }}:{{ mattermost_port }}"
    volumes:
      - "{{ mattermost_deploy_dir }}/config:/mattermost/config"
      - "{{ mattermost_deploy_dir }}/data:/mattermost/data"
      - "{{ mattermost_deploy_dir }}/logs:/mattermost/logs"
      - "{{ mattermost_deploy_dir }}/plugins:/mattermost/plugins"
      - "{{ mattermost_deploy_dir }}/client/plugins:/mattermost/client/plugins"
    user: "{{ mattermost_user }}:{{ mattermost_group }}"

