[web]
web_node ansible_host="{{ secret_web_ip }}" ansible_user=web ansible_ssh_private_key_file=~/web_key

[app]
app_node ansible_host="{{ secret_app_ip }}" ansible_user=app ansible_ssh_private_key_file=~/app_key

[db]
db_node ansible_host="{{ secret_db_ip }}" ansible_user=db ansible_ssh_private_key_file=~/db_key

[managed:children]
web
app
db
