---
nginx_port: 443
nginx_server_name: "{{ web_host }}"
nginx_ssl_certificate_path: "/etc/ssl/certs/mattermost.crt"
nginx_ssl_certificate_key_path: "/etc/ssl/private/mattermost.key"
enable_zabbix_monitor_subpath: false
zabbix_monitor_subpath: "/zabbix_monitor"
zabbix_monitor_upstream_host: "{{ secret_zabbix_monitor_upstream_host }}"
zabbix_monitor_upstream_port: "{{ secret_zabbix_monitor_upstream_port }}"
