---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Configure fail2ban for SSH (managed nodes - default)
  copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 86400
      findtime = 60
      maxretry = 3
      banaction = ufw

      [sshd]
      enabled = true
      port = ssh
      filter = sshd
      logpath = /var/log/auth.log
      maxretry = 3
    mode: "0644"
  when: "'control' not in group_names"
  notify: restart fail2ban

- name: Configure fail2ban for SSH (Control Node - aggressive)
  copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      banaction = ufw

      [sshd]
      enabled  = true
      port     = ssh
      filter   = sshd
      logpath  = /var/log/auth.log
      maxretry = 3
      findtime = 60
      bantime  = 604800
    mode: "0644"
  when: "'control' in group_names"
  notify: restart fail2ban

- name: Enable and start fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes
