---
- name: Acquiring web's public IP
  hosts: web
  gather_facts: false
  tasks:
    - name: Fetch web's Public IP from ipify
      uri:
        url: https://api.ipify.org
        return_content: yes
      register: web_public_ip_response
    - name: Set web's public IP fact
      set_fact:
        web_public_ip: "{{ web_public_ip_response.content }}"

- name: Applying security enforcement on all nodes
  hosts: all
  become: yes
  roles:
    - common
    - ssh_hardening
    - firewall
    - fail2ban
    - auto_updates

- name: Setup DB tier
  hosts: db
  become: yes
  roles:
    - postgresql

- name: Setup App tier
  hosts: app
  become: yes
  roles:
    - mattermost

- name: Setup Web tier
  hosts: web
  become: yes
  roles:
    - nginx

