---
- name: Install PostgreSQL dependencies
  apt:
    name:
      - postgresql-{{ postgres_version }}
      - postgresql-contrib-{{ postgres_version }}
      - python3-psycopg2
    state: present

- name: Ensure PostgreSQL is running and enabled
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Create Mattermost database
  postgresql_db:
    name: "{{ db_name }}"
    port: "{{ postgres_port }}"
    state: present
  become: yes
  become_user: postgres

- name: Create Mattermost database user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    db: "{{ db_name }}"
    port: "{{ postgres_port }}"
    priv: ALL
    state: present
  become: yes
  become_user: postgres

- name: Allow remote connections to PostgreSQL
  lineinfile:
    path: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    regexp: "^#?listen_addresses = .*"
    line: "listen_addresses = '*'"
  notify: Restart PostgreSQL

- name: Change PostgreSQL port
  lineinfile:
    path: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    regexp: "^#?port = .*"
    line: "port = {{ postgres_port }}"
  notify: Restart PostgreSQL

- name: Disable SSL in postgresql.conf
  lineinfile:
    path: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
    regexp: "^#?ssl ="
    line: "ssl = off"
  notify: Restart PostgreSQL

- name: Configure pg_hba.conf - restrict to App Node IP
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
    owner: postgres
    mode: "0640"
  notify: Restart PostgreSQL
